apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: default
  labels:
    app: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - name: ftp-data
    protocol: TCP
    port: 21
  - name: ftp-connection
    protocol: TCP
    port: 20
  - name: pftp-data-0
    protocol: TCP
    port: 30000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: services/ftps
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - ./liveness.sh
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
        - containerPort: 21
        - containerPort: 20
        - containerPort: 30032
