apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: services/wordpress
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - ./liveness.sh
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
        - name: http
          containerPort: 5050
---

apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: default
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  ports:
  - port: 5050
    protocol: TCP
    name: http
