apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: services/wordpress
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 5050
        volumeMounts:
        - name: wordpress-data
          mountPath: /wordpress
      volumes:
      - name: wordpress-data
        persistentVolumeClaim:
          claimName: wordpress-pv-claim
---

apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: default
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  ports:
  - port: 5050
    protocol: TCP
    name: http
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
